import type { VideoNode } from '../engine/effects/VideoNode'
import {
  ChromaticAberrationNode,
  ColorGradeNode,
  EdgeSharpenNode,
  FeedbackLoopNode,
  FocusJitterNode,
  GazeTunnelNode,
  GlassVeilNode,
  GrainNode,
  GridHintNode,
  HazeNode,
  InterferenceNode,
  IntrusionBurstNode,
  PulseNode,
  SalienceCompetitionNode,
  SoftBlurNode,
  SomaticPulseNode,
  TemporalSmearNode,
  VignetteNode,
} from '../engine/effects'

export const NODE_FACTORY: Record<string, () => VideoNode> = {
  grain: () => new GrainNode(),
  vignette: () => new VignetteNode(),
  chromatic_aberration: () => new ChromaticAberrationNode(),
  // Canonical profile name.
  // Legacy alias: some profiles and dimension mappings use "chroma_aberration" as a short form.
  chroma_aberration: () => new ChromaticAberrationNode(),
  temporal_smear: () => new TemporalSmearNode(),
  color_grade: () => new ColorGradeNode(),
  haze: () => new HazeNode(),
  soft_blur: () => new SoftBlurNode(),
  edge_sharpen: () => new EdgeSharpenNode(),
  pulse: () => new PulseNode(),
  interference: () => new InterferenceNode(),
  focus_jitter: () => new FocusJitterNode(),
  feedback_loop: () => new FeedbackLoopNode(),
  grid_hint: () => new GridHintNode(),
  gaze_tunnel: () => new GazeTunnelNode(),
  somatic_pulse: () => new SomaticPulseNode(),
  intrusion_burst: () => new IntrusionBurstNode(),
  salience_competition: () => new SalienceCompetitionNode(),
  glass_veil: () => new GlassVeilNode(),
}
