/**
 * Phase 11: Knowledge base automation.
 * Generates docs/generated/conditions-catalog.md and preset-schema (JSON + MD).
 * Run: npm run docs:gen
 *
 * Do not edit generated files by hand.
 */

import { readFileSync, readdirSync, writeFileSync, mkdirSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { dirname } from 'node:path'
import { z, toJSONSchema } from 'zod'
import { profileSchema, catalogSchema } from '../src/conditions/schema.ts'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')

const GENERATED_DIR = join(ROOT, 'docs', 'generated')
// Canonical source for condition data
const CONDITIONS_DIR = join(ROOT, 'src', 'conditions')
const CATALOG_PATH = join(CONDITIONS_DIR, 'catalog.json')
const PROFILES_DIR = join(CONDITIONS_DIR, 'profiles')

const DO_NOT_EDIT = '<!-- Generated by scripts/gen-docs.ts — do not edit by hand. -->'

type Catalog = z.infer<typeof catalogSchema>
type Profile = z.infer<typeof profileSchema>

function loadCatalog(): Catalog {
  const raw = JSON.parse(readFileSync(CATALOG_PATH, 'utf-8'))
  const parsed = catalogSchema.safeParse(raw)
  if (!parsed.success) throw new Error(`Catalog validation failed: ${JSON.stringify(parsed.error.flatten())}`)
  return parsed.data
}

function loadProfiles(): Profile[] {
  const files = readdirSync(PROFILES_DIR).filter((f) => f.endsWith('.json'))
  const profiles: Profile[] = []
  for (const f of files) {
    const path = join(PROFILES_DIR, f)
    const raw = JSON.parse(readFileSync(path, 'utf-8'))
    const parsed = profileSchema.safeParse(raw)
    if (!parsed.success) {
      console.warn(`[gen-docs] Skip ${f}: validation failed`)
      continue
    }
    profiles.push(parsed.data)
  }
  return profiles.sort((a, b) => a.id.localeCompare(b.id))
}

function videoNodeNames(p: Profile): string[] {
  return (p.video_stack ?? []).map((n) => n.node).filter(Boolean)
}

function audioNodeNames(p: Profile): string[] {
  const chain = p.audio_stack?.chain
  if (!chain) return []
  return chain.map((n) => n.node).filter(Boolean)
}

function allNodeNames(p: Profile): string[] {
  const v = videoNodeNames(p)
  const a = audioNodeNames(p)
  return [...new Set([...v, ...a])].sort()
}

function generateConditionsCatalogMd(catalog: Catalog, profiles: Profile[]): string {
  const catalogById = new Map(catalog.conditions.map((c) => [c.id, c]))
  const lines: string[] = [
    '# Conditions catalog (generated)',
    '',
    DO_NOT_EDIT,
    '',
    'Summary of all conditions and their profiles (id, label, tags, safety, nodes).',
    '',
    '## Table',
    '',
    '| id | label | tags | safety (intensity max) | nodes |',
    '|----|-------|------|------------------------|-------|',
  ]

  for (const p of profiles) {
    const entry = catalogById.get(p.id)
    const tags = entry?.tags?.length ? entry.tags.join(', ') : '—'
    const intensityMax = p.safety?.intensity_max ?? '—'
    const nodes = allNodeNames(p).join(', ') || '—'
    const label = p.label.replace(/\|/g, '\\|')
    lines.push(`| ${p.id} | ${label} | ${tags} | ${intensityMax} | ${nodes} |`)
  }

  lines.push('')
  lines.push('## Per-condition details')
  lines.push('')

  for (const p of profiles) {
    const entry = catalogById.get(p.id)
    const desc = entry?.description ?? p.summary ?? ''
    lines.push(`### ${p.label} (\`${p.id}\`)`)
    lines.push('')
    if (desc) {
      lines.push(desc)
      lines.push('')
    }
    const warnings = p.safety?.warnings ?? []
    if (warnings.length > 0) {
      lines.push('**Warnings:**')
      lines.push('')
      for (const w of warnings) {
        lines.push(`- ${w}`)
      }
      lines.push('')
    }
    lines.push(`**Nodes:** ${allNodeNames(p).join(', ') || 'none'}`)
    lines.push('')
  }

  return lines.join('\n')
}

function generatePresetSchemaJson(): string {
  const jsonSchema = toJSONSchema(profileSchema, {
    target: 'draft-07',
    unrepresentable: 'any',
  }) as Record<string, unknown>
  jsonSchema.$comment = 'Generated by scripts/gen-docs.ts — do not edit by hand.'
  return JSON.stringify(jsonSchema, null, 2)
}

function generatePresetSchemaMd(schemaJson: string): string {
  const required = ['id', 'label', 'summary', 'framing', 'experience_dimensions', 'safety', 'video_stack']
  const lines: string[] = [
    '# Preset (profile) JSON Schema (generated)',
    '',
    DO_NOT_EDIT,
    '',
    'This document describes the JSON Schema for condition profile files under `src/conditions/profiles/<id>.json`.',
    '',
    '## Required keys',
    '',
    'The schema validates the following as **required**:',
    '',
    ...required.map((k) => `- \`${k}\``),
    '',
    '| Key | Meaning |',
    '|-----|--------|',
    '| `id` | Condition identifier (must match catalog and filename). |',
    '| `label` | Human-readable name shown in the UI. |',
    '| `summary` | One-paragraph, non-diagnostic description. |',
    '| `framing` | Metaphor framing block (non-diagnostic). |',
    '| `experience_dimensions` | Dimension references + weights. |',
    '| `safety` | Safety defaults, clamps, warnings, Reduced Motion policy. |',
    '| `video_stack` | Ordered array of video node definitions (can be empty). |',
    '',
    'Other important keys: `safety` (intensity_default, intensity_max, warnings), `audio_stack`, `ui.controls`, `reactive.analyser_to_params`.',
    '',
    '## JSON Schema',
    '',
    'The machine-readable JSON Schema is embedded below and also written to `preset-schema.json`.',
    '',
    '```json',
    schemaJson,
    '```',
    '',
  ]
  return lines.join('\n')
}

function main(): void {
  mkdirSync(GENERATED_DIR, { recursive: true })

  const catalog = loadCatalog()
  const profiles = loadProfiles()

  const conditionsCatalogMd = generateConditionsCatalogMd(catalog, profiles)
  writeFileSync(join(GENERATED_DIR, 'conditions-catalog.md'), conditionsCatalogMd, 'utf-8')
  console.log('Written docs/generated/conditions-catalog.md')

  const schemaJson = generatePresetSchemaJson()
  writeFileSync(join(GENERATED_DIR, 'preset-schema.json'), schemaJson, 'utf-8')
  console.log('Written docs/generated/preset-schema.json')

  const presetSchemaMd = generatePresetSchemaMd(schemaJson)
  writeFileSync(join(GENERATED_DIR, 'preset-schema.md'), presetSchemaMd, 'utf-8')
  console.log('Written docs/generated/preset-schema.md')
}

main()
